config/routes.rb
Rails.application.routes.draw do
  resources :players_queues
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/players_queue.rb
class PlayersQueue < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  skip_before_action :verify_authenticity_token
end

app/controllers/players_queues_controller.rb
class PlayersQueuesController < ApplicationController
  before_action :set_players_queue, only: %i[show edit update destroy]

  # GET /players_queues or /players_queues.json
  def index
    @players_queues = PlayersQueue.all.limit(10).order(created_at: :desc)
    render json: @players_queues
  end

  # GET /players_queues/1 or /players_queues/1.json
  def show
  end

  # GET /players_queues/new
  def new
    @players_queue = PlayersQueue.new
  end

  # GET /players_queues/1/edit
  def edit
  end

  # POST /players_queues or /players_queues.json
  def create
    @players_queue = PlayersQueue.new(players_queue_params)

    respond_to do |format|
      if @players_queue.save
        format.html { redirect_to players_queue_url(@players_queue), notice: "Players queue was successfully created." }
        format.json { render :show, status: :created, location: @players_queue }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @players_queue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players_queues/1 or /players_queues/1.json
  def update
    respond_to do |format|
      if @players_queue.update(players_queue_params)
        format.html { redirect_to players_queue_url(@players_queue), notice: "Players queue was successfully updated." }
        format.json { render :show, status: :ok, location: @players_queue }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @players_queue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players_queues/1 or /players_queues/1.json
  def destroy
    @players_queue.destroy!

    respond_to do |format|
      format.html { redirect_to players_queues_url, notice: "Players queue was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_players_queue
    @players_queue = PlayersQueue.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def players_queue_params
    puts params
    params.require(:players_queue).permit(:players, :user_id, :room_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
    render json: @user
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    if @user.save
      render json: @user
    else
      render json: @user.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy!

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/players_queues_helper.rb
module PlayersQueuesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MaimaiAntrianBackendRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/players_queues/_form.html.erb
<%= form_with(model: players_queue) do |form| %>
  <% if players_queue.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(players_queue.errors.count, "error") %> prohibited this players_queue from being saved:</h2>

      <ul>
        <% players_queue.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :players, style: "display: block" %>
    <%= form.text_field :players %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.label :room_id, style: "display: block" %>
    <%= form.number_field :room_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/players_queues/_players_queue.html.erb
<div id="<%= dom_id players_queue %>">
  <p>
    <strong>Players:</strong>
    <%= players_queue.players %>
  </p>

  <p>
    <strong>User:</strong>
    <%= players_queue.user_id %>
  </p>

  <p>
    <strong>Room:</strong>
    <%= players_queue.room_id %>
  </p>

</div>

app/views/players_queues/edit.html.erb
<h1>Editing players queue</h1>

<%= render "form", players_queue: @players_queue %>

<br>

<div>
  <%= link_to "Show this players queue", @players_queue %> |
  <%= link_to "Back to players queues", players_queues_path %>
</div>

app/views/players_queues/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Players queues</h1>

<div id="players_queues">
  <% @players_queues.each do |players_queue| %>
    <%= render players_queue %>
    <p>
      <%= link_to "Show this players queue", players_queue %>
    </p>
  <% end %>
</div>

<%= link_to "New players queue", new_players_queue_path %>

app/views/players_queues/new.html.erb
<h1>New players queue</h1>

<%= render "form", players_queue: @players_queue %>

<br>

<div>
  <%= link_to "Back to players queues", players_queues_path %>
</div>

app/views/players_queues/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @players_queue %>

<div>
  <%= link_to "Edit this players queue", edit_players_queue_path(@players_queue) %> |
  <%= link_to "Back to players queues", players_queues_path %>

  <%= button_to "Destroy this players queue", @players_queue, method: :delete %>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>